name: Deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.3
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: TMap/TMap.csproj
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{ secrets.NUGET_DEPLOY_KEY }}
